# Sidebar navigation

- label: "Overview"
  link: "/"
- label: Work
  items:
    - label: "Client eComm Project"
      link: "/work/usagi-bakery"
    - label: "Project/Task Tracking App"
      link: "/work/ops-party"
    - label: "WebRTC Party Chat"
      link: "/work/partyy"
- label: Profile
  items:
    - label: "About me"
      link: "/profile/about-me"
    - label: "Experience"
      link: "/profile/experience"
    - label: "Contact"
      link: "/profile/contact"
- label: Links
  items:
    - label: "Github"
      link: https://github.com/jrodshua
    - label: "LinkedIn"
      link: https://www.linkedin.com/in/jrodshua/
    - label: "Twitter"
      link: https://twitter.com/jrodshua
